### ISSUE TITLE
Not showing and unable to generate 

### ISSUE THREAD

**Issue by mraiur** [pererinha/NotThatUselessProjectReport#2]
Tried to run it with the shortcut:
On Windows or Linux Ctrl + Shift + U

Also not showing in command list:
Ctrl + Shift + P and search for “Generate a not useless report about your project”

PC: 
Dell Optiplex 790 
OS: Windows 7 64
SublimeText 3 build 3059

If you need more information please msg :)

**Comment by dreaganluna** [comment]
same problem, different PC.

**Comment by pererinha** [comment]
@mraiur @dreaganluna 
Thanks for reporting it :)

I haven't tested it at Windows, when I did I realized that it was having some problems importing packages. It is fixed now. 

I published the update.
